In [1]:
%pip install pandas
import pandas as pd
import numpy as np
pd.options.display.max_columns = 100

Requirement already satisfied: pandas in c:\digivate projects\bank_prototype_v_2_0\venv\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in c:\digivate projects\bank_prototype_v_2_0\venv\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\digivate projects\bank_prototype_v_2_0\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\digivate projects\bank_prototype_v_2_0\venv\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\digivate projects\bank_prototype_v_2_0\venv\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\digivate projects\bank_prototype_v_2_0\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.2.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
df = pd.read_csv("data/output/customers_education_loan_dataset.csv")
df.head()

,id,applicant_age,applicant_gender,applicant_education_level,applicant_region,applicant_marital_status,applicant_cibil,applicant_networth,kyc_status,date,co_applicant,rm_relation,co_applicant_age,rm_skillset,loan_type,university,unfavourable_profession,co_applicant_cibil,co_applicant_networth,co_applicant_salary,co_applicant_existing_emi,loan_size,loan_duration,day,month,label
0,0,32,F,Masters,Rural,Married,502,8700000,Compliant,2024-11-22,Not-Available,0,0,Knowledgeable Regarding Education Loans,Domestic,Grade B,False,0,0,0,0,3400000,6,22,11,Not-Good
1,1,35,F,Bachelors,Urban,Married,535,9050000,Compliant,2024-11-26,Available,2,55,Knowledgeable Regarding Education Loans,International,Grade B,True,438,7650000,3200000,8000,7200000,12,26,11,Not-Good
2,2,34,M,Bachelors,Urban,Married,615,4200000,Compliant,2024-08-11,Available,0,48,Knowledgeable Regarding Education Loans,Domestic,Grade A,False,803,5850000,2700000,6000,2800000,6,11,8,Good
3,3,33,M,Bachelors,Urban,Married,536,3700000,Compliant,2024-09-16,Available,2,36,Knowledgeable Regarding Education Loans,International,Grade A,False,821,1100000,550000,0,9800000,4,16,9,Fair
4,4,35,F,Bachelors,Urban,Married,872,7500000,Compliant,2024-12-01,Available,1,43,Follows Through,International,Grade A,False,846,8700000,2650000,5000,9400000,4,1,12,Fair

In [8]:
df["label"].value_counts()

label
Fair        2031568
Not-Good    1762197
Good        1206235
Name: count, dtype: int64

In [10]:
df[(df["applicant_networth"] <= df['loan_size']) & (df["co_applicant"] == "Not-Available")]

,id,applicant_age,applicant_gender,applicant_education_level,applicant_region,applicant_marital_status,applicant_cibil,applicant_networth,kyc_status,date,co_applicant,rm_relation,co_applicant_age,rm_skillset,loan_type,university,unfavourable_profession,co_applicant_cibil,co_applicant_networth,co_applicant_salary,co_applicant_existing_emi,loan_size,loan_duration,day,month,label
15,15,50,F,Masters,Rural,Married,738,450000,Compliant,2024-05-11,Not-Available,2,0,Follows Through,International,Grade A,False,0,0,0,0,7600000,5,11,5,Not-Good
67,67,26,M,Masters,Rural,Married,797,8350000,Compliant,2024-11-14,Not-Available,1,0,Knowledgeable Regarding Education Loans,Domestic,Grade A,False,0,0,0,0,9800000,10,14,11,Not-Good
77,77,32,F,Masters,Urban,Married,694,1550000,Compliant,2024-09-16,Not-Available,1,0,Follows Through,Domestic,Grade A,True,0,0,0,0,1800000,8,16,9,Not-Good
85,85,22,F,Bachelors,Rural,Married,628,450000,Compliant,2024-02-13,Not-Available,1,0,Low Effort,Domestic,Grade C,False,0,0,0,0,7400000,4,13,2,Not-Good
88,88,21,F,High School Diploma,Rural,Unmarried,627,450000,Compliant,2024-04-05,Not-Available,0,0,Knowledgeable Regarding Education Loans,International,Grade A,False,0,0,0,0,6600000,3,5,4,Not-Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4999830,4999830,38,F,Bachelors,Urban,Married,713,2600000,Compliant,2024-05-19,Not-Available,1,0,Knowledgeable Regarding Education Loans,Domestic,Grade A,False,0,0,0,0,4000000,4,19,5,Not-Good
4999834,4999834,43,M,Masters,Rural,Married,762,4850000,Compliant,2024-05-10,Not-Available,1,0,Knowledgeable Regarding Education Loans,International,Grade A,True,0,0,0,0,4900000,11,10,5,Not-Good
4999851,4999851,43,M,Bachelors,Urban,Married,581,7450000,Non-Compliant,2024-04-26,Not-Available,1,0,Knowledgeable Regarding Education Loans,Domestic,Grade A,False,0,0,0,0,8100000,5,26,4,Not-Good
4999944,4999944,40,F,Bachelors,Urban,Unmarried,862,800000,Compliant,2024-03-06,Not-Available,2,0,Knowledgeable Regarding Education Loans,International,Grade B,False,0,0,0,0,3600000,6,6,3,Not-Good
4999967,4999967,34,F,Bachelors,Urban,Married,862,9000000,Compliant,2024-11-05,Not-Available,1,0,Follows Through,International,Grade A,False,0,0,0,0,9700000,8,5,11,Not-Good

In [45]:
eligible_emi = ((7600000/12)*0.5) -  8000
actual_loan = ((eligible_emi) * (1-(1/((1+(0.12/12))**(9*12))))) / (0.12/12)   
actual_loan

20328104.459330954

In [46]:
(((actual_loan-3000000)/100000) * 0.01)

1.7328104459330953

In [51]:
eligible_emi

308666.6666666667

In [54]:
num = np.log10(eligible_emi) - (np.log10(eligible_emi-(3000000*(0.12/12))))
den = np.log10(1+(0.12/12))
(num/den)//12

np.float64(0.0)

In [56]:
(9 - 0.0)*0.01

0.09

In [23]:
#emi calculator
loan_size = 10000000
interest_rate = 0.15
loan_duration = 15

emi = (loan_size*(interest_rate/12)*((1+(interest_rate/12))**(loan_duration*12)))/((1+(interest_rate/12))**(loan_duration*12)-1)
emi

139958.71187445737

In [33]:
#salary vs emi
((800000/12)*0.9 - emi)*0.0001

-7.995871187445737

In [123]:
(((57 - (21+3))*100000)/500000)*0.1

0.66